# Generated by Django 3.1.3 on 2020-11-26 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_or_rent', models.CharField(choices=[('S', 'Sell'), ('R', 'Rent')], max_length=1)),
                ('property_type', models.CharField(max_length=4)),
                ('image', models.ImageField(upload_to='images/')),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('bedroom', models.IntegerField()),
                ('built_up_area', models.FloatField()),
                ('built_up_unit', models.CharField(choices=[('1', 'm²'), ('2', 'cm²'), ('3', 'mm²')], max_length=1)),
                ('carpet_area', models.FloatField()),
                ('carpet_unit', models.CharField(choices=[('1', 'm²'), ('2', 'cm²'), ('3', 'mm²')], max_length=1)),
                ('resale_or_new', models.CharField(choices=[('R', 'Resale'), ('N', 'New Booking')], default=('R', 'Resale'), max_length=1)),
                ('property_floor', models.CharField(max_length=20)),
                ('total_floor', models.IntegerField()),
                ('availability', models.CharField(choices=[('R', 'Ready to Move'), ('U', 'Under Construction')], max_length=1)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(related_name='realbuy_posts', to=settings.AUTH_USER_MODEL)),
                ('ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
