# Generated by Django 3.1.3 on 2020-11-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realbuy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_floor',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('C', 'Commercial'), ('F', 'Furnished Home'), ('L', 'Land and Plot'), ('R', 'Rental')], max_length=10),
        ),
    ]
