# Generated by Django 3.1.3 on 2020-11-27 11:53

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('realbuy_app', '0002_auto_20201127_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='built_up_unit',
            field=models.CharField(choices=[('1', 'm²'), ('2', 'cm²'), ('3', 'sq.ft')], max_length=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='carpet_unit',
            field=models.CharField(choices=[('1', 'm²'), ('2', 'cm²'), ('3', 'sq.ft')], max_length=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_floor',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Commercial', 'Commercial'), ('Furnished Home', 'Furnished Home'), ('Land and Plot', 'Land and Plot'), ('Rental', 'Rental')], max_length=46),
        ),
    ]
