# Generated by Django 3.1.3 on 2020-11-27 12:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('realbuy_app', '0003_auto_20201127_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('commercial', 'Commercial'), ('furnished home', 'Furnished Home'), ('land and plot', 'Land and Plot'), ('rental', 'Rental')], max_length=46),
        ),
    ]
