# Generated by Django 3.1.3 on 2020-12-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realbuy_app', '0005_auto_20201201_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathroom',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedroom',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='built_up_area',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='built_up_unit',
            field=models.CharField(choices=[('CENTS', 'cents'), ('SQM', 'sq.m'), ('SQFT', 'sq.ft')], max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='carpet_area',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='carpet_unit',
            field=models.CharField(choices=[('CENTS', 'cents'), ('SQM', 'sq.m'), ('SQFT', 'sq.ft')], max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_floor',
            field=models.IntegerField(blank=True),
        ),
    ]
