# Generated by Django 3.1.3 on 2020-12-21 12:41

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('realbuy_app', '0007_auto_20201221_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='availability',
            field=models.CharField(choices=[('ready to move', 'Ready to Move'), ('under construction', 'Under Construction')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='built_up_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='built_up_unit',
            field=models.CharField(choices=[('CENTS', 'cents'), ('SQM', 'sq.m'), ('SQFT', 'sq.ft')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='carpet_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='carpet_unit',
            field=models.CharField(choices=[('CENTS', 'cents'), ('SQM', 'sq.m'), ('SQFT', 'sq.ft')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_floor',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='resale_or_new',
            field=models.CharField(choices=[('resale', 'Resale'), ('new', 'New Booking')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_floor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
