# Generated by Django 3.1.3 on 2020-12-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realbuy_app', '0008_auto_20201221_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedroom',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
