# Generated by Django 3.1.3 on 2020-12-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realbuy_app', '0010_auto_20201221_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='user', max_length=30),
        ),
    ]
