# Generated by Django 3.1.3 on 2021-02-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realbuy_app', '0014_auto_20210203_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, default='user@mail.com', max_length=254, null=True),
        ),
    ]
